spring.application.name=backend

# ==========================
# Database Configuration
# ==========================

spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway
spring.datasource.username=root
spring.datasource.password=QMJdfLfYFolTKGQdegeUYHXFXyIykSac

# ==========================
# JPA Configuration
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================
# Server
# ==========================

server.port=${PORT:8080}
